services:
  sem_work:
    build: .
    container_name: sem_work_container
    ports:
      - "8080:8080"
    links:
      - postgres
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_container/postgres"
      - "SPRING_DATASOURCE_USERNAME=postgres"
      - "SPRING_DATASOURCE_PASSWORD=password"
  postgres:
    image: postgres:alpine
    container_name: postgres_container
    environment:
      POSTGRES_PASSWORD: password